### ISSUE TITLE
Install Wayland DEB on Debian 12 error libwx_gtk3u_html-3.0.so.0

### ISSUE THREAD

**Issue by lutfiajib** [federico-terzi/espanso#1793]
Just download latest version Espanso Wayland Debian v.2.2.1 from Github, and got error 

1. Download from Githut using espanso-debian-wayland-amd64.deb
2. sudo apt install ./espanso-debian-wayland-amd64.deb
3. call espanso from console
4. Got this error: 

```
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

- OS: Debian 12
- Version: v2.2.1 (latest version)

## Momentary fix

As devs continue to work on this, [this comment](https://github.com/espanso/espanso/issues/1793#issuecomment-1919055522) fixes the problem for the time being.

**Comment by guillaume-martin** [comment]
I have the same bug with espanso-debian-x11-amd64.deb v.2.2.1 (OS: Debian 12)

**Comment by Rody-Oldenhuis** [comment]
Same here on Ubuntu 23.10/Mantic.

**Comment by FluffMe** [comment]
Same here on X11 deb.

Used an AppImage version as a workaround for now. Works with no issues.

**Comment by Rody-Oldenhuis** [comment]
[Building from source](https://espanso.org/docs/install/linux/#wayland-compile) also seems to work OK (using `cargo-make` `v0.37.5` / Ubuntu 23.10)

**Comment by gavinlaking** [comment]
Sadly, the first step of building from source is failing for me on Debian 12 Bookworm and Debian testing as `Unable to locate package libwxgtk3.0-gtk3-dev`.

Edit:

I can however install `libwxgtk3.2-gtk3-dev`, so I did!. Unfortunately, despite compiling again from source, it still fails when running `espanso --version`; with the following error:

```
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

Edit 2:

The compiled version appears to run fine (at least `./target/release/espanso --version` doesn't crash), until it is moved or copied to `/usr/local/bin/espanso` via `sudo mv target/release/espanso /usr/local/bin/espanso`. I don't know enough about Cargo to deduce what is actually happening.

Edit 3:

For those triaging, I was just having a look through the issues and noticed this one; https://github.com/espanso/espanso/issues/1739 which is outlines similar issues to this, but no solution either.

**Comment by zchap26** [comment]
Same issue with espanso-debian-wayland-amd64.deb v2.2.1 on Debian 12 Bookworm.

**Comment by yue-dongchen** [comment]
@Rody-Oldenhuis Have you tested running it? I will compile it tomorrow if it works for you. Also on 23.10.

**Comment by yue-dongchen** [comment]
> For those triaging, I was just having a look through the issues and noticed this one; #1739 which is outlines similar issues to this, but no solution either.

I suspect the pre-built .deb cannot locate _libwx_gtk3u_html-3.0.so.0_ because of [this commit](https://github.com/espanso/espanso/commit/4a9739f98e062ec6aa29dcf53acd35010e29f7a9#diff-b9b872cf52f4e68169da8d1ec848cdabbd530d2043503963e75d366f2503b422R92) relaxing compilation, plus the package then being compiled with _libwxgtk3.0-gtk3-dev_. If Espanso is compatible with wxWidgets 3.2, then the issue should only be compilation. I will try tomorrow.

**Comment by Rody-Oldenhuis** [comment]
> @Rody-Oldenhuis Have you tested running it? I will compile it tomorrow if it works for you. Also on 23.10.

@yue-dongchen Yes I did; I could do text replacements just fine. Though, I ran it on my dev machine, which is not _quite_ a pristine environment..

**Comment by jdnixx** [comment]
I get this on the X11 version with Kubuntu 23.10.

**Comment by ysz0507** [comment]
I get this problem on Debian 12 with Wayland. 
The problem occurred on the versions v2.2.1 and v2.2.0. The installation of [v2.1.8](https://github.com/espanso/espanso/releases/tag/v2.1.8) solved the problem for me.

**Comment by gavinlaking** [comment]
Tried your approach @ysz0507 on Debian testing, "just incase", sadly no dice;

```
$ sudo dpkg -i ~/Downloads/espanso-debian-wayland-amd64.deb 
Selecting previously unselected package espanso-wayland.
(Reading database ... 289203 files and directories currently installed.)
Preparing to unpack .../espanso-debian-wayland-amd64.deb ...
Unpacking espanso-wayland (2.1.8) ...
dpkg: dependency problems prevent configuration of espanso-wayland:
 espanso-wayland depends on libwxgtk3.0-gtk3-0v5; however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.
 espanso-wayland depends on libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg); however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.
 espanso-wayland depends on libwxbase3.0-0v5 (>= 3.0.4+dfsg); however:
  Package libwxbase3.0-0v5 is not installed.

dpkg: error processing package espanso-wayland (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 espanso-wayland
```

I can't install `libwxgtk3.0`, as it isn't available:

```
$ sudo apt search libwxgtk3
Sorting... Done
Full Text Search... Done
libwxgtk3.2-1/testing,now 3.2.4+dfsg-2 amd64 [installed,automatic]
  wxWidgets Cross-platform C++ GUI toolkit (GTK 3 runtime)

libwxgtk3.2-dev/testing,now 3.2.4+dfsg-2 amd64 [installed]
  wxWidgets Cross-platform C++ GUI toolkit (GTK 3 development)
```

**Comment by davidvv** [comment]
I had the same issue on ubuntu 23.10.1. Fixed it editing the sources file `/etc/apt/sources.list` like this:

`sudo nano /etc/apt/sources.list `

added the source: deb http://cz.archive.ubuntu.com/ubuntu focal main universe   (Use your desired mirror from:  https://packages.ubuntu.com/focal/amd64/libwxgtk3.0-gtk3-dev/download)



```
sudo apt update
sudo apt install libwxgtk3.0-gtk3-dev
```

then you need to:
```
espanso service register
espanso start
```

and should be good to go


_Alternatively to the first steps, one can install the needed libwxgtk... from here: one can install it from here too: https://www.ubuntuupdates.org/package/core/jammy/universe/base/libwxgtk3.0-gtk3-dev_

@smeech edit:

The aforementioned workaround is something that is not recommended per Debian's official docs: https://wiki.debian.org/DontBreakDebian, and compiling from the repo is a safer option until we can make a Release.

Namely, mixing repositories from different distros (i.e. doing a "FrankenDebian") can break your install in subtle ways that won't be noticed until much later down the road. Certainly avoid installing any further older packages, perhaps by removing the source above, once you've downloaded `libwxgtk3.0-gtk3-dev`.

**Comment by cskmnrpt** [comment]
It worked. Thank you @davidvv.

**Comment by ghost** [comment]
This does not work on Debian 12, the packages are a bit spotty

- [libwxgtk3.0](https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=libwxgtk3.0) :red_circle: 
- [libwxgtk3.1](https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=libwxgtk3.1) :red_circle: 
- [libwxgtk3.2](https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=libwxgtk3.2) :heavy_check_mark: 

Installing 3.2 produces following error

```
$ espanso service register
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by officiallymarky** [comment]
Still have this issue trying to install X11 on 23.10

**Comment by Tzalim** [comment]
Hope you're all doing well. I've got a bit of a snag and could use some help here.

I'm running MX Linux KDE 23.2, Debian 12.5, and x11. I'm trying to install libwxgtk3.0-gtk3-dev to get Espanso up and running. I followed the usual steps, like updating my sources.list with "deb http://archive.ubuntu.com/ubuntu focal-updates main" and importing the keys.

However, when I try to register the espanso service, I get this error: "espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory."

I used to be on Garuda (Arch) Linux, where everything worked perfectly. Since moving to MX Linux for the MX Snapshot feature, I've hit this roadblock.

Any insights on fixing this and getting Espanso to play nice? Thanks.

**Comment by officiallymarky** [comment]
Any update on this issue?

**Comment by AucaCoyan** [comment]
It's a bit stalled because of this PR #1849 . I think we could separate the fix of this bug from the other bug, but I prefer to fix both if it's still possible

**Comment by Lastofthefirst** [comment]
Any updates here? @AucaCoyan

**Comment by hhl** [comment]
Same issue on debian unstable trixi/sid!

**Comment by AucaCoyan** [comment]
I'm still debugging the issue. We have a couple of problems here, and it's hard to take a direction without consequences.

`./.github/scripts/ubuntu/Dockerfile` uses ubuntu:18.04 to begin with, this builds the .dpkg focused on an ubuntu version previous than 22.04, [and the compilation guide](https://github.com/espanso/espanso/blob/dev/Compilation.md#linux) says it needs different dependencies (exactly `libwxgtk3.0-gtk3-dev` instead of `libwxgtk3.2-dev`)
Okay, so why don't we use a newer LTS version of ubuntu then? because the latest LTS is 22.04, and it builds the same dpkg than we currently have now. The next LTS is scheduled to be 24.04, and it's unreleased as of today.

So, after LTS 24.04 is released, does it mean we bump the dependencies and drop support for ubuntu 22.04 and earlier? I don't know, it's a cost to assume. Certainly the old users can use espanso v2.2.1 and be happy, but it's not without a cost

As other notes: why do we even need  `libwxgtk*` library? can we change the GUI and drop it? would that mean support to all ubuntu versions? We need to find out 🤔

**Comment by davidvv** [comment]
I’d clearly say fix it and leave behind who wants to stay behind…

**Comment by AucaCoyan** [comment]
Yep! I would do that too! but I want to be cancelous of other people who prefer not to have the latest and greatest, for whatever reason they have

**Comment by AucaCoyan** [comment]
I did a test PR #1925 , trying to use `debian:latest` to build the image. In my pc the dpkg built correctly. I'll wait a couple of days before merging. It's a possible (i.e. viable) solution

**Comment by officiallymarky** [comment]
I haven’t been able to reinstall for months so having a working install would be a big win.

**Comment by jdrx99** [comment]
@AucaCoyan do you think you will be able to provide a guide / solution for debian with xfce / x11 as well?

**Comment by AucaCoyan** [comment]
Hello! Just a quick update: I couldn't find time to dedicate to this issue, I've been dealing with a lot of things in the espanso org. Thank you for your patience!

**Comment by officiallymarky** [comment]
Is there any solution for this to get it installed, I haven't been able to install espanso in months once I got on 23.10.

**Comment by eudennis** [comment]
Just for anyone else who falls here, using the AppImage worked for me.

**Comment by officiallymarky** [comment]
> Just for anyone else who falls here, using the AppImage worked for me.

I ended up going this route, I've been trying to get it reinstalled for a while, and gave up and just went to app image.  Worked great.  I recommend using Gear Lever as it helps keeps the versions in tact and make shortcuts for your menu and keep them organized.

**Comment by Lastofthefirst** [comment]
It looks like the AppImage is not for Wayland, only x11. Will has anyone tried manual compilation?

**Comment by officiallymarky** [comment]
> It looks like the AppImage is not for Wayland, only x11. Will has anyone tried manual compilation?

I did in the past and I got it working.  I haven’t had much luck with any of them lately but appimage does work for me on x11 but on Wayland I am unable to use espanso

**Comment by R4dicalEdward** [comment]
Hi, I'm using Debian 12 “bookworm” with Wayland. I recently followed the instructions from the official `espanso` documentation for manual compilation. Initially, I replaced `libwxgtk3.0-gtk3-dev` with `libwxgtk3.2-dev` because the former is no longer available in the Debian repository. It looks like the `espanso` documentation has been updated to reflect this change. Currently, I'm running `espanso` version 2.2.1, and it works like a charm—no problems at all.

**Comment by michaelaye** [comment]
Same issue for Ubuntu 24.04 LTS (which has Wayland by default so no AppImage solution) and espanso 2.2.1.

**Comment by smeech** [comment]
> Hi, I'm using Debian 12 “bookworm” with Wayland. I recently followed the instructions from the official `espanso` documentation for manual compilation. Initially, I replaced `libwxgtk3.0-gtk3-dev` with `libwxgtk3.2-dev` because the former is no longer available in the Debian repository. It looks like the `espanso` documentation has been updated to reflect this change. Currently, I'm running `espanso` version 2.2.1, and it works like a charm—no problems at all.

Thank you. I've updated the documentation for this item a couple of times in the last twenty-four hours. As far as I can tell, the compilation works with either library, in either version, hence ultimately settling on an apt regex for this item.

I'll leave this open for now, in case I'm mistaken!

**Comment by michaelaye** [comment]
I went through the compile instructions without errors (wayland, Ubuntu 24.04 LTS), but expansion is not happening. `espanso status` says it's running. How can I debug?

**Comment by dwbfox** [comment]
> I went through the compile instructions without errors (wayland, Ubuntu 24.04 LTS), but expansion is not happening. `espanso status` says it's running. How can I debug?

Unfortunately it may be erroring for the previously mentioned dependency. Compiling it from source doesn't automatically resolve it unless you change whatever rust package is wanting this library:

```
sudo apt-file search libwx_gtk3u_html-3.0.so.0
sudo apt-file search libwx_gtk3u_html
libwxgtk3.2-1t64: /usr/lib/x86_64-linux-gnu/libwx_gtk3u_html-3.2.so.0
libwxgtk3.2-1t64: /usr/lib/x86_64-linux-gnu/libwx_gtk3u_html-3.2.so.0.2.2
libwxgtk3.2-dev: /usr/lib/x86_64-linux-gnu/libwx_gtk3u_html-3.2.so
```

On Ubuntu 24.04, it seems the version of libwx_gtk3u_html being provided is the newer `3.2`.

In my year or so of using Espanso I have yet to actually utilize the GUI and hence the GTK library. I wish there was a config flag to just disable this and do away with it.

**Comment by michaelaye** [comment]
But then, if this is only for a GUI, I don't understand, even if the wrong GTK library is linked, that an expansion is simply not happening without any error message?

**Comment by michaelaye** [comment]
Also, the compile instructions indicate that 3.2 is fine? https://github.com/espanso/espanso/blob/dev/Compilation.md#necessary-dependencies

**Comment by dwbfox** [comment]
> Also, the compile instructions indicate that 3.2 is fine? https://github.com/espanso/espanso/blob/dev/Compilation.md#necessary-dependencies

For builds compiled for X11 it seems.

Since I'm on 24.04 and Wayland, I compiled it with `NO_X11=true` and it fails for the 3.0 dependency

```
$ espanso
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

I just want to figure out what package or dependency is asking for 3.0 so I can just brute force it to use 3.2 somehow.

**Comment by stylerw** [comment]
Same issue here, compiling for Wayland within a Fedora 39 VM environment following the up-to-date instructions, and then running on Fedora Kinoite 40.

**Comment by davidawad** [comment]
I had this issue on a new framework laptop with latest ubuntu. 

I fixed it with an edit to 

```
sudo vim /etc/apt/sources.list.d/ubuntu.sources
```
then added this; 

```
Types: deb
URIs: http://cz.archive.ubuntu.com/ubuntu/
Suites: focal
Components: main universe
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

```

once that was done, and update and install worked
```
sudo apt-get update
sudo apt install libwxgtk3.0-gtk3-dev
```

**Comment by dwbfox** [comment]
> I had this issue on a new framework laptop with latest ubuntu.
> 
> I fixed it with an edit to
> 
> ```
> sudo vim /etc/apt/sources.list.d/ubuntu.sources
> ```
> 
> then added this;
> 
> ```
> Types: deb
> URIs: http://cz.archive.ubuntu.com/ubuntu/
> Suites: focal
> Components: main universe
> Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
> ```
> 
> once that was done, and update and install worked
> 
> ```
> sudo apt-get update
> sudo apt install libwxgtk3.0-gtk3-dev
> ```

While this will work, you're mixing the 20.04 and 24.04 repo which could have unintended consequences when you try to install other apps/dependencies, let alone those that might depend on `> libwxgtk3.0` 

Really what needs to be done is Espanso or its dependencies to be able to use libwxgtk3.2 or above for newer Wayland builds to work.

**Comment by pacossac** [comment]
Same problem  when trying to install the .deb package. I'm running Debian Bookworm/testing (Trixie). 

(I also tried flathub, which didn't work for me after installation).

**Comment by AucaCoyan** [comment]
According to my tests, #1925 resolves the problem. Please report any issue if it keeps happening!
Cheers and enjoy

**Comment by stylerw** [comment]
I'm still seeing this error after pulling down the latest git. Compiling for Wayland within a Fedora 39 VM environment following the up-to-date instructions, and then running on Fedora Kinoite 40.

> espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory

Just to make sure all is clear, this comes from a fresh clone, a cargo make install, and then `cargo make --profile release --env NO_X11=true build-binary`, copying the result into my home directory, and running *any* espanso command. I get the same error when I extract the bin out of the .deb file.

Thanks for your hard work here, though!

**Comment by qwertychouskie** [comment]
What is the output of `which espanso`?  It sounds like you are still running an old binary.

**Comment by stylerw** [comment]
> What is the output of `which espanso`? It sounds like you are still running an old binary.

I actually ran through the process twice, the first time with a git pull, and then second time wiping everything (including the binary) and doing a full clone, checking the `which espanso` each time, and the binary which I created with the cargo make and copied over is the one which was listed. In fact, this system (being a wayland environment) has never had a working Espanso binary.  So, I don't think that's the problem here.

**Comment by AucaCoyan** [comment]
Thank you! I re opened the issue. Maybe it's caused for another thing and it wasn't solved

**Comment by AucaCoyan** [comment]
Hello again! 
@stylerw , I tried to install a VM of Fedora Kinoite 40 and after it boots the screen turns black with a grey cursor blinking. I tried to troubleshoot but didn't succeed.
Does anybody else see the error of the issue? `libwx_gtk*`. I don't know if it just happens in fedora or other distros too

**Comment by tony1661** [comment]
I am having this  issue on Linux Mint 22 (Ubuntu 24.04). I upgraded from 21.3 (Ubuntu 22.04) and started having this issue. It seems that espanso wants libwxgtk3.0 to be installed but only libwxgtk3.2 is available in the repos.

I am using X11

**Comment by tony1661** [comment]
I was able to get around this by using the AppImage install method listed [here](https://espanso.org/docs/install/linux/#appimage-x11)

**Comment by robinvandernoord** [comment]
I got it to work with the help of #1925:
```
# in the dev branch, commit 335f667
docker build -t espanso-ubuntu .  -f .github/scripts/Dockerfile
docker run --rm -v "$(pwd):/shared" espanso-ubuntu espanso/.github/scripts/ubuntu/build_deb.sh
sudo dpkg -i ./espanso-debian-x11-amd64.deb
```

This is for Linux Mint with x11, I can't test it with wayland right now but a `espanso-debian-wayland-amd64.deb` was also generated.

**Comment by laurenspriem** [comment]
I'm on ubuntu 24.04 and have tried all methods of installation without success, except for compiling from source. Am I interpreting this thread correct that compiling from source also doesn't fix it?

**Comment by tony1661** [comment]
@laurenspriem Appimage worked for me

**Comment by laurenspriem** [comment]
> @laurenspriem Appimage worked for me

On ubuntu 24.04 with Wayland? I have tried the AppImage but couldn't get it to work

**Comment by tony1661** [comment]
> > @laurenspriem Appimage worked for me
> 
> On ubuntu 24.04 with Wayland? I have tried the AppImage but couldn't get it to work

On Linux Mint 23 which is based in 24.04

**Comment by kankaristo** [comment]
> > > @laurenspriem Appimage worked for me
> > 
> > 
> > On ubuntu 24.04 with Wayland? I have tried the AppImage but couldn't get it to work
> 
> On Linux Mint 23 which is based in 24.04

@tony1661, you mentioned in an earlier comment that you're using X11. The [AppImage installation method](https://espanso.org/docs/install/linux/#appimage-x11) is listed under "Install on X11", so it doesn't appear to be supported on Wayland. Do you have it working on Wayland?

**Comment by tony1661** [comment]
@kankaristo no sorry, I misread and didn't realize some others were talking about Wayland.

I had the issue with Deb version on x11 but no issue with Appimage on x11.

**Comment by laurenspriem** [comment]
In my experience the AppImage doesn't work on Wayland. So my original question remains: anyone got it working on Wayland by compiling from source?

I miss Espanso :(

**Comment by officiallymarky** [comment]
> In my experience the AppImage doesn't work on Wayland. So my original question remains: anyone got it working on Wayland by compiling from source?
> 
> I miss Espanso :(

I ended up compiling it myself again.  Only way to get it to work right now.

**Comment by laurenspriem** [comment]
@officiallymarky From your earlier comments I'm assuming you're on x11? I want to know if compiling works for wayland

**Comment by AucaCoyan** [comment]
It does work for wayland, but you may need some help with the libraries. Please send a message in the [espanso discord](https://discord.gg/DFcCNDg7bB) and we will help you!

**Comment by officiallymarky** [comment]
> @officiallymarky From your earlier comments I'm assuming you're on x11? I want to know if compiling works for wayland

I have compiled on both, but I am currently on Wayland and using it.

**Comment by stylerw** [comment]
For people using Fedora Silverblue/Kinoite who've gotten this error, here's how I've gotten it working:

- Layer wxGTK-devel (`sudo rpm-ostree install wxGTK-devel`) and then reboot
    - This *must* be layered into your system, that's not just a requirement to build
- Use Distrobox/Toolbox to make the development environment to compile (I used a Fedora 39 container)
- Compile from the Git Repo, copy the executable to your choice of binary folder
- Run the setcap command
- Now it should run as expected

Certainly not as easy as in the AppImage days, but difficult Espanso is better than no Espanso.

**Comment by mbootsman** [comment]
Same issue here on a freshly installed Ubuntu 24.04.1 installation using X11 and the deb installation.
Used the AppImage option for now, and that works.

**Comment by zdover23** [comment]
> I had this issue on a new framework laptop with latest ubuntu.
> 
> I fixed it with an edit to
> 
> ```
> sudo vim /etc/apt/sources.list.d/ubuntu.sources
> ```
> 
> then added this;
> 
> ```
> Types: deb
> URIs: http://cz.archive.ubuntu.com/ubuntu/
> Suites: focal
> Components: main universe
> Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
> ```
> 
> once that was done, and update and install worked
> 
> ```
> sudo apt-get update
> sudo apt install libwxgtk3.0-gtk3-dev
> ```

This procedure worked for me on Ubuntu 24.04. I understand that this might create some kind of package conflict for me in the future, but I will cross that bridge when I come to it.

I upgraded from Ubuntu 22.04 to Ubuntu 24.04 and got this error message:

> espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory

Following @davidawad's procedure worked for me, and took less than seventy seconds.

**Comment by shawnyeager** [comment]
I can confirm that on a fresh installation of Ubuntu 24.04.1, this problem persists. Pity, as this looks like a great app to replace part of my migrated macOS workflow.

**Comment by audwn-ie** [comment]
Hey folks

For those using Ubuntu 24, do not install **libwxgtk3.0-gtk3-dev**

I horsed around with the "fixings" on this post and it ended up breaking my gdm3 locking me out without login. Had to remove gdm3 completly and use lightdm. It really broke my Ubuntu in a way I wont waste more time fixing.

I spent last couple of months trying to fix espanso and its sad that there is no working solution.

The time I saved until today using espanso in the past is now wasted trying to help fix something the devs dont give a F.

Im just moving on to some other software. xoxo

**Comment by tony1661** [comment]
@and-stuber AppImage worked well for me on Ubuntu/Linux Mint

**Comment by AucaCoyan** [comment]
@and-stuber 
> The time I saved until today using espanso in the past is now wasted trying to help fix something the devs dont give a F.

Please be civil.

> Im just moving on to some other software. xoxo

Great! That's why we use oss. Have a great time anyways!

**Comment by johnfisherman** [comment]
Yeah, it's November 2024 and I ran into this issue on Ubuntu LTS 24.04, using Wayland. I am positively impressed with the traction espanso has on Linux, go FOSS!

Anyway, help?!

**Comment by j-lakeman** [comment]
Pls see #2126

**Comment by Lancelotmay** [comment]
I tried to install espanso latest version today and met the same issue. 
I fully understood the security concerns mentioned above to make an official release.
So I tried to build from source.  Following are the commands I used on ubuntu24..04 latest update. It take a few mins if the network and the CPU are not too bad.

``` bash
sudo apt update && sudo apt install build-essential git wl-clipboard libxkbcommon-dev libdbus-1-dev ^libwxgtk3\.[0-9].*-dev$ libssl-dev
sudo apt install cargo
git clone https://github.com/espanso/espanso
cd espanso/
sudo apt install rustup
rustup update
cargo search cargo-make
cargo install cargo-make
cargo make --profile release --env NO_X11=true build-binary 
sudo mv target/release/espanso /usr/local/bin/espanso
sudo setcap "cap_dac_override+p" $(which espanso)
espanso service register
espanso start
```
If it could not start successfully, check the log by:
espanso log

Especially, for my case, I need to switch to English keyboard to get it start.

Hope it could help.

Many thanks for the contributors for this useful program!

**Comment by AucaCoyan** [comment]
Hi! I'm trying it again with cargo-deb dependencies.
If you are courageous enough, would you give me a little of your time trying if this pr #2173 works?
If you are willing, you need to compile and run the binary. Then report if this error keeps happening or not. I suspect there will be some problems in wlroots desktops (hyperland, sway and the family)

**Comment by yetiinabox** [comment]
@Lancelotmay -- thank you - your instructions for compiling on 24.04 with Wayland worked a treat. Now to test.

**Comment by smeech** [comment]
> @Lancelotmay -- thank you - your instructions for compiling on 24.04 with Wayland worked a treat. Now to test.

You might wish to wait - @AucaCoyan has a PR #2173 ready that fixes the problem anyway - I've recently [tested](https://discord.com/channels/884163483409731584/1013902954350248008/1315460758762688533) it on X11, Wayland and Sway. You could help us, by trying that, however.

**Comment by AucaCoyan** [comment]
Hello everyone! After a few installs and tests, we got this resolved 🤞🤞 (I hope!)
Please, try to download the latest development version and compile it again. I hope it works! ❤️  It does in my machine and a couple more.

If anything happens, I'm more inclined to create a new issue with the problems there, to keep a new track and don't disturb 30+ people in notifications 🙌

**Comment by silentworks** [comment]
@AucaCoyan tested it on Ubuntu 24 with wayland and it works correctly after compiling the latest dev version locally.

**Comment by AucaCoyan** [comment]
Tadaaaaa!
Thank you 💯

**Comment by johnfisherman** [comment]
Hey! This worked for me after I followed @Lancelotmay's compiling directions. Thanks to all of you for your code and support. Keep it up!

**Comment by j-lakeman** [comment]
I know this thread is mainly about Debian stable, still FYI: installed it on Debian Sid following [the docs](https://espanso.org/docs/install/linux/#deb-wayland) but with the [latest pre-release](https://github.com/espanso/espanso/releases/tag/v2.2.2) and it's working splendid.
Awesome work guys!

**Comment by AucaCoyan** [comment]
Thank you for trying! Many people use Debian unstable, so it brings me peace of mind it also works there 🎉

**Comment by Sispheor** [comment]
Hello there! So for Ubuntu 24.04 users we should wait couple days for a release with the fix?

**Comment by smeech** [comment]
> Hello there! So for Ubuntu 24.04 users we should wait couple days for a release with the fix?

For the time being, you'll need to compile if you want to benefit from the fix. A new release is some way off due to certification problems.

**Comment by Sispheor** [comment]
Tried the command provided above but no luck
```
sudo apt install build-essential git libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev ^libwxgtk3\.[0-9].*-dev$ libssl-dev
zsh: no matches found: ^libwxgtk3.[0-9].*-dev$
```

**Comment by salvadornico-bax** [comment]
> Tried the command provided above but no luck
> 
> ```
> sudo apt install build-essential git libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev ^libwxgtk3\.[0-9].*-dev$ libssl-dev
> zsh: no matches found: ^libwxgtk3.[0-9].*-dev$
> ```

I had a similar issue, had to add quotes around the regex one. So:
```
sudo apt install build-essential git libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev '^libwxgtk3\.[0-9].*-dev$' libssl-dev
```

**Comment by smeech** [comment]
It doesn't seem to be working currently. You may need `sudo apt install libwxgtk3.*-gtk3-dev`, or try `libwxgtk3.2-dev`.

**Comment by johnfisherman** [comment]
> Tried the command provided above but no luck
> 
> ```
> sudo apt install build-essential git libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev ^libwxgtk3\.[0-9].*-dev$ libssl-dev
> zsh: no matches found: ^libwxgtk3.[0-9].*-dev$
> ```

This worked for me on Ubuntu 24.04:

`sudo apt-get install libwxgtk3.2-dev`

**Comment by Sispheor** [comment]
Thanks you guys! It works fine. here all the commands I used on Ubuntu mate 24.04 (with X11)

```bash
sudo apt install build-essential git libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev '^libwxgtk3\.[0-9].*-dev$' libssl-dev
sudo apt install cargo rustup
git clone https://github.com/espanso/espanso
cd espanso
git checkout dev
rustup install stable
rustup default stable
cargo install cargo-make
cargo make --profile release build-binary
sudo mv target/release/espanso /usr/local/bin/espanso
sudo setcap "cap_dac_override+p" $(which espanso)
espanso service register
espanso start
```

```
:thanks 
```

**Comment by daetanbhuck** [comment]
> Hello everyone! After a few installs and tests, we got this resolved 🤞🤞 (I hope!) Please, try to download the latest development version and compile it again. I hope it works! ❤️ It does in my machine and a couple more.
> 
> If anything happens, I'm more inclined to create a new issue with the problems there, to keep a new track and don't disturb 30+ people in notifications 🙌

Installing 2.2.2 fixed the issue for me, too (edit: Debian). Thanks so much!

**Comment by kankaristo** [comment]
> Thanks you guys! It works fine. here all the commands I used on Ubuntu mate 24.04 (with X11)
> 
> ```shell
> sudo apt install cargo rustup
> ```

On my machine (Ubuntu 24.04), `rustup` conflicts with `cargo`, so I had to uninstall `cargo` and just install `rustup` (which includes `cargo`). But after that I could compile Espanso and it's working fine!

(hoping for a .deb soon)

**Comment by AucaCoyan** [comment]
that's weird. I always recommend installing rustup from the rust website:
https://www.rust-lang.org/tools/install
Sometimes debian and ubuntu-based systems "freeze" some dependencies to prevent breaking changes (and introducing other bugs in the process).
There is no perfect solution for package management 😥

**Comment by fuguesoft** [comment]
On Debian 12 and the temporary fix linked above is a bit confusing
Do I add this whole line:

> deb http://cz.archive.ubuntu.com/ubuntu focal main universe (Use your desired mirror from: https://packages.ubuntu.com/focal/amd64/libwxgtk3.0-gtk3-dev/download)

To my `etc/apt/sources.list` file?

**Comment by AucaCoyan** [comment]
It's not necessary anymore. If you compile from source it shouldn't happen.
With that line Debian is able to find the `libwx` in another source, but you should install the dependencies like [the documentation says](https://espanso.org/docs/install/linux/#wayland-compile) 🙏

**Comment by adiabatic** [comment]
I'm running Debian Stable 12 and installing Rust via Homebrew.

In passing, I had to put quotes around the asterisk in the install-the-essential-components line, like so, because I'm using `fish` as my main shell:

```
> sudo apt update && sudo apt install build-essential git wl-clipboard libxkbcommon-dev libdbus-1-dev libssl-dev "libwxgtk3.*-dev"
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                                      
Hit:3 http://deb.debian.org/debian bookworm-backports InRelease                                    
Hit:4 http://security.debian.org/debian-security bookworm-security InRelease                       
Reading package lists... Done            
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libwxgtk3.0-dev' for glob 'libwxgtk3.*-dev'
Note, selecting 'libwxgtk3.2-dev' for glob 'libwxgtk3.*-dev'
```

It _might_ be a good idea to add quotes to the instructions in general as long as doing so doesn't mess up bash and/or zsh users.

Anyway…

I couldn't get the final build to work:

```
~/Projects/Others/espanso (dev) > cargo make --profile release --env NO_X11=true build-binary
[cargo-make] INFO - cargo make 0.34.0
[cargo-make] WARN - #####################################################################
[cargo-make] WARN - #                                                                   #
[cargo-make] WARN - #                                                                   #
[cargo-make] WARN - #                  NEW CARGO-MAKE VERSION FOUND!!!                  #
[cargo-make] WARN - #                 Current: 0.34.0, Latest: 0.37.23                  #
[cargo-make] WARN - #    Run 'cargo install --force cargo-make' to get latest version   #
[cargo-make] WARN - #                                                                   #
[cargo-make] WARN - #                                                                   #
[cargo-make] WARN - #####################################################################
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: build-binary
[cargo-make] INFO - Profile: release
[cargo-make] INFO - Running Task: build-binary
[cargo-make] INFO - Execute Command: Command {
    program: "cargo",
    args: [
        "cargo",
        "install",
        "--force",
        "rust-script",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
    create_pidfd: false,
}
    Updating crates.io index
  Downloaded rust-script v0.35.0
  Downloaded 1 crate (52.9 KB) in 0.07s
  Installing rust-script v0.35.0
    Updating crates.io index
     Locking 90 packages to latest compatible versions
  Downloaded anstream v0.6.18
  Downloaded anstyle-query v1.1.2
  Downloaded anstyle v1.0.10
  Downloaded clap v4.5.23
  Downloaded pulldown-cmark-escape v0.11.0
  Downloaded clap_lex v0.7.4
  Downloaded option-ext v0.2.0
  Downloaded dirs-sys v0.4.1
  Downloaded strsim v0.11.1
  Downloaded humantime v2.1.0
  Downloaded unicase v2.8.1
  Downloaded toml_datetime v0.6.8
  Downloaded serde_spanned v0.6.8
  Downloaded is_terminal_polyfill v1.70.1
  Downloaded utf8parse v0.2.2
  Downloaded tempfile v3.15.0
  Downloaded env_logger v0.11.6
  Downloaded getopts v0.2.21
  Downloaded shell-words v1.1.0
  Downloaded anstyle-parse v0.2.6
  Downloaded dirs v5.0.1
  Downloaded colorchoice v1.0.3
  Downloaded toml v0.8.19
  Downloaded env_filter v0.1.3
  Downloaded clap_builder v4.5.23
  Downloaded indexmap v2.7.0
  Downloaded toml_edit v0.22.22
  Downloaded is-terminal v0.4.13
  Downloaded winnow v0.6.22
  Downloaded pulldown-cmark v0.12.2
  Downloaded hashbrown v0.15.2
  Downloaded 31 crates (1.3 MB) in 0.20s
   Compiling libc v0.2.169
   Compiling version_check v0.9.5
   Compiling typenum v1.17.0
   Compiling memchr v2.7.4
   Compiling serde v1.0.217
   Compiling generic-array v0.14.7
   Compiling utf8parse v0.2.2
   Compiling anstyle-parse v0.2.6
   Compiling aho-corasick v1.1.3
   Compiling colorchoice v1.0.3
   Compiling is_terminal_polyfill v1.70.1
   Compiling regex-syntax v0.8.5
   Compiling anstyle-query v1.1.2
   Compiling anstyle v1.0.10
   Compiling anstream v0.6.18
   Compiling rustix v0.38.42
   Compiling bitflags v2.6.0
   Compiling cfg-if v1.0.0
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.15.2
   Compiling regex-automata v0.4.9
   Compiling serde_spanned v0.6.8
   Compiling toml_datetime v0.6.8
   Compiling indexmap v2.7.0
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling winnow v0.6.22
   Compiling option-ext v0.2.0
   Compiling log v0.4.22
   Compiling pulldown-cmark v0.12.2
   Compiling linux-raw-sys v0.4.14
   Compiling regex v1.11.1
   Compiling strsim v0.11.1
   Compiling clap_lex v0.7.4
   Compiling unicode-width v0.1.14
   Compiling clap_builder v4.5.23
   Compiling toml_edit v0.22.22
   Compiling getopts v0.2.21
   Compiling env_filter v0.1.3
   Compiling dirs-sys v0.4.1
   Compiling digest v0.10.7
   Compiling getrandom v0.2.15
   Compiling cpufeatures v0.2.16
   Compiling pulldown-cmark-escape v0.11.0
   Compiling fastrand v2.3.0
   Compiling once_cell v1.20.2
   Compiling humantime v2.1.0
   Compiling unicase v2.8.1
   Compiling env_logger v0.11.6
   Compiling tempfile v3.15.0
   Compiling sha1 v0.10.6
   Compiling dirs v5.0.1
   Compiling clap v4.5.23
   Compiling toml v0.8.19
   Compiling is-terminal v0.4.13
   Compiling shell-words v1.1.0
   Compiling rust-script v0.35.0
    Finished `release` profile [optimized] target(s) in 1m 07s
  Installing /home/comatoast/.cargo/bin/rust-script
   Installed package `rust-script v0.35.0` (executable `rust-script`)
[cargo-make] INFO - Execute Command: Command {
    program: "rust-script",
    args: [
        "rust-script",
        "/tmp/comatoast/fsio/BXkd6byVTL.rs",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
    create_pidfd: false,
}
Using profile: Release
Using Wayland feature
Building with default modulo
Calling with args: ["build", "--release", "--manifest-path", "espanso/Cargo.toml", "-p", "espanso", "--no-default-features", "--features", "wayland modulo vendored-tls"]
  Downloaded memmap2 v0.8.0
  Downloaded xcursor v0.3.3
  Downloaded memmap2 v0.9.4
  Downloaded wait-timeout v0.2.0
  Downloaded rustls-pemfile v1.0.2
  Downloaded hyper-rustls v0.23.2
  Downloaded wayland-cursor v0.31.1
  Downloaded bytemuck_derive v1.6.0
  Downloaded wayland-protocols-wlr v0.2.0
  Downloaded tokio-rustls v0.23.4
  Downloaded webpki v0.22.2
  Downloaded xkbcommon v0.7.0
  Downloaded polling v3.6.0
  Downloaded bytemuck v1.15.0
  Downloaded calloop v0.12.4
  Downloaded wayland-csd-frame v0.3.0
  Downloaded wayland-protocols v0.31.2
  Downloaded nom v6.1.2
  Downloaded smithay-client-toolkit v0.18.1
  Downloaded sct v0.7.0
  Downloaded calloop-wayland-source v0.2.0
  Downloaded cursor-icon v1.1.0
  Downloaded webpki-roots v0.22.6
  Downloaded xkeysym v0.2.0
  Downloaded rustls v0.20.8
  Downloaded 25 crates (1.6 MB) in 0.27s
   Compiling libc v0.2.161
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling log v0.4.22
   Compiling pkg-config v0.3.19
   Compiling jobserver v0.1.32
   Compiling quote v1.0.35
   Compiling version_check v0.9.2
   Compiling cc v1.0.73
   Compiling syn v2.0.93
   Compiling memchr v2.7.4
   Compiling getrandom v0.2.2
   Compiling typenum v1.14.0
   Compiling once_cell v1.19.0
   Compiling lazy_static v1.5.0
   Compiling thiserror v1.0.56
   Compiling ppv-lite86 v0.2.10
   Compiling serde v1.0.217
   Compiling pin-project-lite v0.2.14
   Compiling rand_core v0.6.2
   Compiling generic-array v0.14.4
   Compiling slab v0.4.9
   Compiling getrandom v0.1.16
   Compiling rand_chacha v0.3.0
   Compiling scopeguard v1.1.0
   Compiling anyhow v1.0.38
   Compiling rand v0.8.3
   Compiling smallvec v1.13.2
   Compiling bitflags v2.4.1
   Compiling siphasher v0.3.6
   Compiling rustix v0.38.32
   Compiling rand_core v0.5.1
   Compiling tracing-core v0.1.32
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling miniz_oxide v0.4.4
   Compiling crossbeam-utils v0.8.21
   Compiling linux-raw-sys v0.4.13
   Compiling tracing v0.1.40
   Compiling ring v0.16.20
   Compiling num_cpus v1.13.0
   Compiling wayland-sys v0.31.5
   Compiling libloading v0.7.0
   Compiling itoa v0.4.7
   Compiling dlib v0.5.2
   Compiling thiserror-impl v1.0.56
   Compiling serde_derive v1.0.217
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling crypto-common v0.1.6
   Compiling wayland-backend v0.3.7
   Compiling aho-corasick v0.7.19
   Compiling memoffset v0.6.5
   Compiling bytes v1.1.0
   Compiling regex-syntax v0.6.27
   Compiling futures-core v0.3.17
   Compiling regex v1.5.5
   Compiling rand v0.7.3
   Compiling phf_shared v0.8.0
   Compiling phf_shared v0.10.0
   Compiling zstd-sys v2.0.13+zstd.1.5.6
   Compiling tokio v1.28.2
   Compiling crossbeam-epoch v0.9.8
   Compiling unicode-xid v0.2.1
   Compiling untrusted v0.7.1
   Compiling scoped-tls v1.0.0
   Compiling spin v0.5.2
   Compiling ryu v1.0.5
   Compiling downcast-rs v1.2.0
   Compiling phf_generator v0.8.0
   Compiling phf_generator v0.10.0
   Compiling block-buffer v0.10.4
   Compiling quick-xml v0.36.2
   Compiling mio v0.8.6
   Compiling socket2 v0.4.9
   Compiling num-traits v0.2.14
   Compiling new_debug_unreachable v1.0.4
   Compiling wayland-client v0.31.6
   Compiling subtle v2.6.1
   Compiling futures-task v0.3.17
   Compiling syn v1.0.67
   Compiling digest v0.10.7
   Compiling wayland-scanner v0.31.5
   Compiling phf_codegen v0.10.0
   Compiling string_cache_codegen v0.5.1
   Compiling futures-util v0.3.17
   Compiling mac v0.1.1
   Compiling fnv v1.0.7
   Compiling zstd-safe v7.2.1
   Compiling http v0.2.4
   Compiling futf v0.1.4
   Compiling markup5ever v0.11.0
   Compiling crossbeam-deque v0.8.1
   Compiling webpki v0.22.2
   Compiling crossbeam-channel v0.5.0
   Compiling inout v0.1.3
   Compiling crc32fast v1.4.2
   Compiling nom v6.1.2
   Compiling thiserror v2.0.9
   Compiling cpufeatures v0.2.1
   Compiling futures-sink v0.3.17
   Compiling equivalent v1.0.1
   Compiling utf-8 v0.7.6
   Compiling crc-catalog v2.4.0
   Compiling futures-channel v0.3.17
   Compiling httparse v1.8.0
   Compiling powerfmt v0.2.0
   Compiling futures-io v0.3.17
   Compiling precomputed-hash v0.1.1
   Compiling serde_json v1.0.62
   Compiling rustls v0.20.8
   Compiling tinyvec_macros v0.1.0
   Compiling adler v1.0.2
   Compiling matches v0.1.9
   Compiling pin-utils v0.1.0
   Compiling hashbrown v0.14.3
   Compiling indexmap v2.2.2
   Compiling tinyvec v1.3.1
   Compiling string_cache v0.8.1
   Compiling deranged v0.3.11
   Compiling crc v3.2.1
   Compiling tendril v0.4.2
   Compiling tokio-util v0.7.3
   Compiling cipher v0.4.4
   Compiling phf v0.10.1
   Compiling hmac v0.12.1
   Compiling sct v0.7.0
   Compiling zeroize_derive v1.4.2
   Compiling thiserror-impl v2.0.9
   Compiling bytemuck_derive v1.6.0
   Compiling time v0.1.44
   Compiling libdbus-sys v0.2.1
   Compiling num-integer v0.1.44
   Compiling lock_api v0.4.11
   Compiling simd-adler32 v0.3.7
   Compiling itoa v1.0.6
   Compiling percent-encoding v2.1.0
   Compiling bitflags v1.2.1
   Compiling hashbrown v0.12.3
   Compiling parking_lot_core v0.9.9
   Compiling time-core v0.1.2
   Compiling num-conv v0.1.0
   Compiling lockfree-object-pool v0.1.6
   Compiling try-lock v0.2.3
   Compiling crossbeam-queue v0.3.5
   Compiling byteorder v1.4.3
   Compiling rayon-core v1.9.3
   Compiling zip v2.2.2
   Compiling bumpalo v3.16.0
   Compiling lzma-rs v0.3.0
   Compiling toml v0.5.8
   Compiling zopfli v0.8.1
   Compiling want v0.3.0
   Compiling time v0.3.37
   Compiling form_urlencoded v1.0.1
   Compiling bytemuck v1.15.0
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/home/comatoast/Projects/Others/espanso/target/release/build/libdbus-sys-777e78db0fe1c2d4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DBUS_1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=DBUS_1_STATIC
  cargo:rerun-if-env-changed=DBUS_1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/comatoast/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libdbus-sys-0.2.1/build.rs:6:70:
  called `Result::unwrap()` on an `Err` value: Failure { command: "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'dbus-1' not found\nPackage 'dbus-1' not found\n" } }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at /tmp/comatoast/fsio/BXkd6byVTL.rs:105:5:
cargo build failed
stack backtrace:
   0:     0x5644532eded6 - <unknown>
   1:     0x56445330e7f3 - <unknown>
   2:     0x5644532d2f7f - <unknown>
   3:     0x5644532edd63 - <unknown>
   4:     0x5644532e0c56 - <unknown>
   5:     0x5644532e0a6b - <unknown>
   6:     0x5644532e1163 - <unknown>
   7:     0x5644532ee276 - <unknown>
   8:     0x5644532ee0d9 - <unknown>
   9:     0x5644532e0cfc - <unknown>
  10:     0x5644532c3610 - <unknown>
  11:     0x5644532c54ad - <unknown>
  12:     0x5644532c3ca3 - <unknown>
  13:     0x5644532c3c99 - <unknown>
  14:     0x5644532dfa20 - <unknown>
  15:     0x5644532c5675 - <unknown>
  16:     0x7f7596a4b24a - <unknown>
  17:     0x7f7596a4b305 - __libc_start_main
  18:     0x5644532c3bc1 - <unknown>
  19:                0x0 - <unknown>
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
```

Did I botch the prerequisites installation somehow?

**Comment by AucaCoyan** [comment]
No, I think you didn't. The line:
```
  called `Result::unwrap()` on an `Err` value: Failure { command: "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'dbus-1' not found\nPackage 'dbus-1' not found\n" } }
```

is suggesting to install `dbus-1.pc` 🤔. I don't understand why `libdbus-1-dev` doesn't fix this. Usually it appears this error when you didn't install `dbus` previously.

TIL `*.pc` files are arch-specific, and can be in different places [stackexchange](https://unix.stackexchange.com/questions/422869/why-are-pc-files-not-listed-in-one-place).
Try with these steps to see what you find: [dlt-daemon github issue](https://github.com/COVESA/dlt-daemon/issues/139#issuecomment-504001926)

**Comment by adiabatic** [comment]
That did it. `find` turned up `/usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc`, and once I added its parent directory to the previously-nonexistent `PKG_CONFIG_PATH` everything installed fine modulo some C++ warnings in `espanso-modulo`.

Thanks!

**Comment by makeyouswag** [comment]
Why would you ever block the AppImage usage of an application? This is borderline schizophrenic. Making users install from the sources or the packages when there's an already built & working version available. Absolutely disappointing.

Worked perfectly fine on Arch, hopped to Debian and stuck for 2 days on the installation. Unacceptable.

**Comment by AucaCoyan** [comment]
Hi all! I'm locking the conversation because the problem seems to be resolved 💯 .
If you have issues, please open a **new** issue so we can support you.

Have a good day!

**Comment by joh6nn** [comment]
@makeyouswag Auca has already locked this, but it feels important to me to respond to both the tone and content of your comment:

> Why would you ever block the AppImage usage of an application? 

I'm not sure where you got the impression that we are blocking it? It doesn't work for some people om Wayland, and we're offering possible workarounds until we're able to fix it, but that's it. The Appimage remains supported and available for download: https://espanso.org/docs/install/linux/#appimage-x11

> This is borderline schizophrenic.

Schizophrenia is characterized by hallucinations and delusions, often ones that are really distressing and upsetting both to the person experiencing them and the people around them. I know this because there are 2 people in my life actively dealing with it right now. And their struggles are not a catch-all synonym for decisions and behavior that you don't understand or agree with. They are real people, not grist for the mill of your frustrations. 

> Making users install from the sources or the packages when there's an already built & working version available. Absolutely disappointing.

We are not "making" anyone do anything, we are suggesting a work around for a problem we aren't currently able to solve otherwise. And if the already built version fixed the problem, then we wouldn't be suggesting the work around.

> Worked perfectly fine on Arch, hopped to Debian and stuck for 2 days on the installation. Unacceptable.

You are free not to accept it? We don't. We're actively working to fix it. But we're a small team of unpaid non-experts working on this in our extremely limited free time. You're welcome to pitch in and help fix it, we appreciate any help we get!

But you are not free to berate or condescend to us. We are doing the best we're able with the time and resources available to us.

You seem to be a motivated and energetic member of the community. Your TextBlaze to Espanso converter looks interesting! I hope you'll join us here and on Discord to help us move Espanso forward.
